variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_PROJECT_DIR}
  SCRIPT_DIR: "scripts"
  ATS_FILE: "tests/integration.ats"

stages:
  - build_and_install
  - update_tpls
  - update_permissions

include:
  - local: .gitlab/os.yml
  - local: .gitlab-ci-machines.yml

.toss3_platform:
  extends: [.on_ruby]

.blueos_platform:
  extends: [.on_lassen]

include:
  - local: .gitlab/scripts.yml
  - local: .gitlab/specs.yml
  - local: .gitlab/jobs.yml
