
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_PROJECT_DIR}
  SCRIPT_DIR: "scripts"

stages:
  - build_and_install
  - update_tpls
  - update_permissions

include:
  - local: .gitlab/machines.yml
  - local: .gitlab/scripts.yml
  - local: .gitlab/specs.yml

# ------------------------------------------------------------------------------
# BUILD JOBS

r_gcc_8_1_0_mvapich2_Debug:
  extends: [.gcc_8_1_0_mvapich2_Debug, .toss_build_and_test, .on_ruby]
  stage: build_and_install

r_gcc_8_3_1_mvapich2:
  extends: [.gcc_8_3_1_mvapich2, .toss_build_and_test, .on_ruby]
  stage: build_and_install

r_gcc_8_3_1_~mpi:
  extends: [.gcc_8_3_1_~mpi, .toss_build_and_test, .on_ruby]
  stage: build_and_install

r_clang_9_0_0_mvapich2:
  extends: [.clang_9_0_0_mvapich2, .toss_build_and_test, .on_ruby]
  stage: build_and_install

#r_oneapi_2022_1_mvapich2:
#  extends: [.oneapi_2022_1_mvapich2, .toss_build_and_test, .on_ruby]
#  stage: build_and_install

l_gcc_8_3_1_spectrum:
  extends: [.gcc_8_3_1_spectrum, .blueos_build_and_test, .on_lassen]
  stage: build_and_install
  
l_gcc_8_3_1_~mpi_Debug:
  extends: [.gcc_8_3_1_~mpi_Debug, .blueos_build_and_test, .on_lassen]
  stage: build_and_install

# ------------------------------------------------------------------------------
# UPDATE TPL JOBS

l_update_tpls:
  extends: [.on_lassen, .blueos_update_tpls, .merge_pr_rule]
  stage: update_tpls

r_update_tpls:
  extends: [.on_ruby, .toss_update_tpls, .merge_pr_rule]
  stage: update_tpls

# ------------------------------------------------------------------------------
# UPDATE PERM JOBS

r_update_permissions:
  extends: [.on_ruby, .toss_update_permissions, .merge_pr_rule]
  stage: update_permissions
