
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}
  BUILD_ROOT: ${CI_PROJECT_DIR}

stages:
  - r_build_and_install
  - r_run_test_suite

.on_ruby:
  tags:
    - shell
    - ruby
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /_qnone/ || $ON_RUBY == "OFF"' #run except if ...
      when: never
    - if: '$CI_JOB_NAME =~ /release_resources/'
      when: always
    - when: on_success

.build_and_test:
  script:
    - srun -N 1 scripts/gitlab/build_and_test.sh


.gcc_8_1_0_mvapich2_t:
  variables:
    SPEC: "gcc@8.1.0^mvapich2"
    LC_MODULES: "gcc/8.1.0"

gcc_8_1_0_mvapich2:
  extends: [.gcc_8_1_0_mvapich2_t, .build_and_test, .on_ruby]
  stage: r_build_and_install

