jobs:
- job: Docker
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    DOCKER_BUILDKIT: '1'
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - task: Docker@2
    inputs:
      command: build

pr: none
