jobs:
- job: Docker
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    DOCKER_BUILDKIT: '1'
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - task: Docker@2
    inputs:
      command: build

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - develop
    - feature/docker-azure-ci
