jobs:
- job: Docker
  timeoutInMinutes: 360
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    DOCKER_BUILDKIT: '1'
  steps:
  - checkout: self
    clean: true
    submodules: recursive
  - task: Docker@2
    inputs:
      command: build
      arguments: --target spheral-build-env-local --tag spheral-build-env
  - task: Docker@2
    inputs:
      command: build
      arguments: --target spheral --tag spheral --network none

pr: none
