name: Generate build env image

on:
  push:
    branches: ["develop","build-env-generator"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/build-env

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-actions@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build docker image
      run: docker build --target spheral-build-env --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

    - name: push docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
